### ISSUE TITLE
Add a bucket model

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLSM.jl#53]
## Purpose
This Issue and connected PRs will add in a simple land model for use in our AMIP simulations. It will be coupled to the atmosphere using the clima coupler and track water and energy on land.

Design of equations:
https://www.overleaf.com/project/625c5f7677155b314c98eb75
Design PR: https://github.com/CliMA/ClimaLSM.jl/pull/43
Coupler Issue: https://github.com/CliMA/ClimaCoupler.jl/issues/41
PR adding soil hydrology + energy: https://github.com/CliMA/ClimaLSM.jl/pull/50
Snow model feature: https://github.com/CliMA/ClimaLSM.jl/issues/61
## Cost/benefits/risks
Very little cost (it takes developer time, but it isn't a hugely complex undertaking)
Large benefit: we have a land model for AMIP, we have a land model that the coupler team can begin coupling to moist atmospheric runs, the land team also begins to see what is required for coupling from an interface point of view, and we can start to understand issues that may arise with different coverage types (soil+snow).
Very little risk - time away from the ClimaLSM interface, but we need a working land model before we need an interface.

## Producers
@jb-mackay 
@kmdeck 
@LenkaNovak 

## Components
An added AbstractLandModel which contains the information needed to initialize, make rhs!, make update_aux! etc. methods for the Bucket model.

## Inputs
See docs for required inputs

## Results and deliverables
Our key deliverable is a land model which, given water fluxes and energy fluxes at the surface, models water and energy content in land, and models surface properties. These surface properties are required for computing the fluxes at the surface, either internally (land standalone) or in the coupler (coupled mode). The model is a set of ODEs which can be run at a Point, or at each coordinate in a Plane or SphericalShell domain. The model has a default set of parameters but these can be changed by the user. 

We will demonstrate this with driver files demonstrating both standalone and coupled modes of operation. We will also look at using flux tower data for atmosphere properties to drive the bucket land model and make sure that the resulting fluxes, T_sfc, and soil water content look appropriate.

QA: at a minimum, conservation of energy and water. 

## Task breakdown
A preliminary list of PRs and a preliminary timeline of PRs, milestones, and key results.
- [X] Design https://github.com/CliMA/ClimaLSM.jl/pull/43
- [x] Soil Bucket Model https://github.com/CliMA/ClimaLSM.jl/pull/50, https://github.com/CliMA/ClimaCoupler.jl/issues/41
- [ ] Soil Bucket Model running with Atmos, using the coupler https://github.com/CliMA/ClimaLSM.jl/pull/66, https://github.com/CliMA/ClimaLSM.jl/pull/65
- [ ] Snow + Soil Bucket Model: https://github.com/CliMA/ClimaLSM.jl/issues/61
- [ ] Snow/Soil Bucket Model running with Atmos, using the coupler
...

## Reviewers
@jb-mackay @LenkaNovak @kmdeck @yairchn (surface fluxes)
