### ISSUE TITLE
Implicit time stepping for the land model

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLSM.jl#54]
## Purpose
This software development adds in implicit timestepping for the soil model, and addresses how this feature fits into the land model interface as a whole.

## Cost/benefits/risks
The benefit is that we can stably run smulations of variably saturated soil without being as restricted in time step length. The cost is developer time. Risks are relatively low, in that we know this is a solvable problem. However, this is necessary for running a dynamic soil model with the atmosphere, so we have some risk in achieving this by ~mid summer.

## Producers
@kmdeck @dennisYatunin @jb-mackay (as interest allows - as it affects the interface in particular)

## Components
Code creating the Jacobian, code for the linsolve function, driver files testing the implicit solver for 3D variably saturated flow.

## Inputs
[A description of the inputs to the solution (designs, references, equations, closures, discussions etc).](https://www.overleaf.com/read/bzkpfxznrkyt)

## Results and deliverables
Key deliverable is a simulation of variably saturated soil on the sphere and a quantification of how much faster we can run simulations with an "optimal" implicit solver vs an explicit solver.

## Task breakdown
A preliminary list of PRs and a preliminary timeline of PRs, milestones, and key results.
- [ ] Create the jacobian for Richards equation. https://github.com/CliMA/ClimaLSM.jl/blob/soil_implicit_solvers/examples/richards_implicit.jl, https://github.com/CliMA/ClimaLSM.jl/pull/55
- [ ] Create the linsolve for these Jacobians (tridiagnonal, one variable)
- [ ] Test out with Richards equation alone - demonstrate computational efficiency improvement over explicit solver. TBD exact test to run
- [ ] Determine how update_aux fits in with implicit and explicit tendencies
- [ ] Repeat with Soil energy and moisture equations, with freeze/thaw

## Reviewers
@kmdeck @dennisYatunin @jb-mackay

**Comment by kmdeck** [comment]
duplicated
